keyboard:
  matrix_positions:
    - [[1,1], [2,1], [3,1], [4,1], [5,1], [6,1],                  [13,1], [14,1], [15,1], [16,1], [17,1], [18,1]]
    - [[1,2], [2,2], [3,2], [4,2], [5,2], [6,2],                  [13,2], [14,2], [15,2], [16,2], [17,2], [18,2]]
    - [[1,3], [2,3], [3,3], [4,3], [5,3], [6,3],                  [13,3], [14,3], [15,3], [16,3], [17,3], [18,3]]
    - [                            [5,4], [6,4], [7,4],   [12,4], [13,4], [14,4]                                ]

  positions:
    - [[1,1], [2,1], [3,1], [4,1], [5,1], [6,1],                  [13,1], [14,1], [15,1], [16,1], [17,1], [18,1]]
    - [[1,2], [2,2], [3,2], [4,2], [5,2], [6,2],                  [13,2], [14,2], [15,2], [16,2], [17,2], [18,2]]
    - [[1,3], [2,3], [3,3], [4,3], [5,3], [6,3],                  [13,3], [14,3], [15,3], [16,3], [17,3], [18,3]]
    - [                            [5,4], [6,4], [7,4],   [12,4], [13,4], [14,4]                                ]

  hands:
    - [Left, Left, Left, Left, Left, Left,                Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left,                Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left,                Right, Right, Right, Right, Right, Right]
    - [                        Left, Left, Left,   Right, Right, Right                            ]

  fingers:
    - [Pinky, Pinky, Ring,  Middle, Pointer, Pointer,                 Pointer, Pointer, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Pointer, Pointer,                 Pointer, Pointer, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Pointer, Pointer,                 Pointer, Pointer, Middle, Ring,  Pinky, Pinky]
    - [                             Thumb,   Thumb,   Thumb,   Thumb, Thumb,   Thumb,                              ]

  key_costs:
    - [25, 20, 14,  5, 14, 17,           17, 14,  5, 14, 20, 25]
    - [ 9,  5,  3,  3,  2,  6,            6,  2,  3,  3,  5,  9]
    - [20, 11, 22, 22, 10, 15,           15, 10, 22, 22, 11, 20]
    - [                 6,  3,  6,    6,  3,  6                ]

  unbalancing_positions:
    - [   2,   1.5, 0.1,   0, 0.1,   2,               2, 0.1,   0, 0.1,   1.5,   2]
    - [   1,     0,   0,   0,   0, 0.5,             0.5,   0,   0,   0,   0,     1]
    - [   2,     0,   0,   0,   0, 1.5,             1.5,   0,   0,   0,   0,     2]
    - [                         0,   0,   0,     0,   0,   0,                     ]

  symmetries:
    - [  9, 10, 11, 12, 13, 14,           14, 13, 12, 11, 10,  9]
    - [ 15, 16, 17, 18, 19, 20,           20, 19, 18, 17, 16, 15]
    - [ 21, 22, 23, 24, 25, 26,           26, 25, 24, 23, 22, 21]
    - [                 27, 28, 29,   29, 28, 27                ]



  plot_template: |2
                ┌───┐                         ┌───┐
            ┌───┤ {{3}} ├───┬───┐         ┌───┬───┤ {{8}} ├───┐
    ┌───┬───┤ {{2}} ├───┤ {{4}} │ {{5}} │         │ {{6}} │ {{7}} ├───┤ {{9}} ├───┬───┐
    │ {{0}} │ {{1}} ├───┤ {{15}} ├───┼───┤         ├───┼───┤ {{20}} ├───┤ {{10}} │ {{11}} │
    ├───┼───┤ {{14}} ├───┤ {{16}} │ {{17}} │         │ {{18}} │ {{19}} ├───┤ {{21}} ├───┼───┤
    │ {{12}} │ {{13}} ├───┤ {{27}} ├─━─┼───┤         ├───┼─━─┤ {{32}} ├───┤ {{22}} │ {{23}} │
    ├───┼───┤ {{26}} ├───┤ {{28}} │ {{29}} │         │ {{30}} │ {{31}} ├───┤ {{33}} ├───┼───┤
    │ {{24}} │ {{25}} ├───┘   └───┴───┘         └───┴───┘   └───┤ {{34}} │ {{35}} │
    └───┴───┘       ┌───┬───┬───┐ ┌───┬───┬───┐       └───┴───┘
                    │ {{36}} │ {{37}} │ {{38}} │ │ {{39}} │ {{40}} │ {{41}} │
                    └───┴───┴───┘ └───┴───┴───┘


  plot_template_short: |2
    {{0}}{{1}}{{2}}{{3}}{{4}}{{5}} {{6}}{{7}}{{8}}{{9}}{{10}}{{11}}
    ⇘{{12}}{{13}}{{14}}{{15}}{{16}} {{17}}{{18}}{{19}}{{20}}{{21}}⇘
     {{22}}{{23}}{{24}}{{25}}{{26}} {{27}}{{28}}{{29}}{{30}}{{31}}

base_layout:
  keys:
    # Row 1
    - - ["x", "X", "ſ", "−", "ξ", "Ξ"]
      - ["v", "V", "…", "⇞", "", "√"]
      - ["l", "L", "_", "⌫", "λ", "Λ"]
      - ["c", "C", "[", "⇡", "χ", "ℂ"]
      - ["w", "W", "]", "⌦", "ω", "Ω"]
      - ["k", "K", "^", "⇟", "κ", "×"]
      - ["h", "H", "!", "¡", "ψ", "Ψ"]
      - ["g", "G", "<", "7", "γ", "Γ"]
      - ["f", "F", ">", "8", "φ", "Φ"]
      - ["q", "Q", "=", "9", "ϕ", "ℚ"]
      - ["y", "Y", "&", "+", "υ", "∇"]
      - ["ß", "ẞ", "@", ".", "ς", "∘"]
    # Row 2 (home row)
    - - ["⇩"]
      - ["u", "U", "\\", "⇱", "", "⊂"]
      - ["i", "I", "/", "⇠", "ι", "∫"]
      - ["a", "A", "{",  "⇣", "α", "∀"]
      - ["e", "E", "}", "⇢", "ε", "∃"]
      - ["o", "O", "*", "⇲", "ο", "∈"]
      - ["s", "S", "?", "¿", "σ", "Σ"]
      - ["n", "N", "(", "4", "ν", "ℕ"]
      - ["r", "R", ")", "5", "ρ", "ℝ"]
      - ["t", "T", "-", "6", "τ", "∂"]
      - ["d", "D", ":", ",", "δ", "Δ"]
      - ["⇘"]
    # Row 3
    - - [""]
      - ["ü", "Ü", "#", "", "", "∪"]
      - ["ö", "Ö", "$", "\t", "ϵ", "∩"]
      - ["ä", "Ä", "|", "⎀", "η", "ℵ"]
      - ["p", "P", "~", "\n", "π", "Π"]
      - ["z", "Z", "`", "↶", "ζ", "ℤ"]
      - ["b", "B", "+", ":", "β", "⇐"]
      - ["m", "M", "%", "1", "μ", "⇔"]
      - [",", "–", '"', "2", "ϱ", "⇒"]
      - [".", "•", "'", "3", "ϑ", "↦"]
      - ["j", "J", ";", ";", "θ", "Θ"]
      - [""]
    # Row 4, containing the spacebar
    - - ["⇚"]
      - ["⇧"]
      - ["\t"]
      - ["⏎"]
      - [" ", " ", " ", "0", " ", " "]
      - ["⇙"]
      - [""]
      - [""]

  fixed_keys:
    - [ false, false, false, false, false, false,                  false, false, false, false, false, false]
    - [  true, false, false, false, false, false,                  false, false, false, false, false,  true]
    - [  true, false, false, false, false, false,                  false, false, false, false, false,  true]
    - [                              true,  true,  true,    true,  true,  true                     ]

  fixed_layers: [2, 3]

  modifiers:
    - Left: ["⇧"]
      Right: ["⇧"]
    - Left: ["⇩"]
      Right: ["⇘"]
    - Left: ["⇚"]
      Right: ["⇙"]
    - Left: ["⇧", "⇚"]
      Right: ["⇧", "⇙"]
    - Left: ["⇩", "⇚"]
      Right: ["⇘", "⇙"]

  layer_costs: [0, 20, 9, 16, 29, 25]
