keyboard:
  matrix_positions:
    - [[0,0],    [1,0], [2,0], [3,0], [4,0], [5,0], [6,0],   [13,0], [14,0], [15,0], [16,0], [17,0], [18,0], [19,0]]
    - [[0,1],          [2,1], [3,1], [4,1], [5,1], [6,1],   [13,1], [14,1], [15,1], [16,1], [17,1], [18,1], [19,1]]
    - [[0,2],            [2,2], [3,2], [4,2], [5,2], [6,2],   [13,2], [14,2], [15,2], [16,2], [17,2], [18,2], [19,2], [20,2]]
    - [[0,3],    [1,3],    [2,3], [3,3], [4,3], [5,3], [6,3],   [13,3], [14,3], [15,3], [16,3], [17,3], [18,3]]
    - [[0,4], [1,4], [2,4],                             [6,4],                        [16,4], [17,4], [18,4], [19,4]]

  positions:
    - [[   0,0],   [   1,0],   [   2,0],   [   3,0],   [   4,0],   [   5,0],   [   6,0],   [   7,0],   [   8,0],   [   9,0],   [   10,0],   [   11,0],   [   12,0],   [   13,0]]
    - [   [0.25,1],   [1.25,1],   [2.25,1],   [3.35,1],   [4.25,1],   [5.25,1],   [6.25,1],   [7.25,1],   [8.25,1],   [9.25,1],   [10.25,1],   [11.25,1],   [12.25,1]]
    - [      [ 0.5,2],   [ 1.5,2],   [ 2.5,2],   [ 3.5,2],   [ 4.5,2],   [ 5.5,2],   [ 6.5,2],   [ 7.5,2],   [ 8.5,2],   [ 9.5,2],   [ 10.5,2],   [ 11.5,2],   [ 12.5,2],   [ 13.5,2]]
    - [[   0,3],  [  1,3],  [1.75,3],   [2.75,3],   [3.75,3],   [4.75,3],   [5.75,3],   [6.75,3],   [7.75,3],   [8.75,3],   [ 9.75,3],   [10.75,3],   [11.75,3]]
    - [      [ 0.5,4],         [   2,4],   [   3,4],                                       [   7,4],                          [   10,4],   [ 11.5,4],   [   12,4],    [   13,4]]

  hands:
    - [Left,    Left, Left, Left, Left, Left, Left,   Right, Right, Right, Right, Right, Right, Right]
    - [Left,       Left, Left, Left, Left, Left,   Right, Right, Right, Right, Right, Right, Right]
    - [Left,         Left, Left, Left, Left, Left,   Right, Right, Right, Right, Right, Right, Right, Right]
    - [Left,    Left,  Left, Left, Left, Left, Left,   Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left,                     Right,                      Right, Right, Right, Right]

  fingers:
    - [Pinky,    Pinky, Pinky, Ring, Middle, Pointer, Pointer,   Pointer, Pointer, Middle, Ring, Pinky, Pinky, Pinky]
    - [Pinky,       Pinky, Ring, Middle, Pointer, Pointer,   Pointer, Pointer, Middle, Ring, Pinky, Pinky, Pinky]
    - [Pinky,          Pinky, Ring, Middle, Pointer, Pointer,   Pointer, Pointer, Middle, Ring, Pinky, Pinky, Pinky, Pinky]
    - [Pinky,    Pinky,   Pinky, Ring, Middle, Pointer, Pointer,   Pointer, Pointer, Middle, Ring, Pinky, Pinky]
    - [Pinky, Ring, Thumb,                          Thumb,                      Thumb, Middle, Ring, Pinky]

  key_costs:
    - [80,   70, 60, 50, 50, 50, 60,   60, 50, 50, 50, 60, 70, 80]
    - [24,      16, 10,  5, 12, 17,   20, 13,  5,  9, 11, 20, 36]
    - [ 9,         5,  3,  3,  3,  6,    6,  3,  3,  3,  5,  9, 30,  6]
    - [20,   16,    19, 22, 22,  9, 30,   10,  8, 20, 20, 17, 19]
    - [ 0,  0,  0,              3,               7,  0,  0,  0]

  unbalancing_positions:
    - [  2,      2,    2,   0,   0,   0,   0,     0,   0,   0,   2,   2,   2,   2]
    - [  2,           1,   0,   0, 0.1,   2,     2, 0.1,   0,   0,   1,   2, 2.5]
    - [  1,             0,   0,   0,   0,   1,     1,   0,   0,   0,   0,   1,   2,   2]
    - [  2,      0,       0, 0.5, 0.5,   0,   2,    0.5,   0, 0.5, 0.5,   0,   2]
    - [  3,   0,   0,                       0,                        0,   0,   0,   3]

  symmetries:
    - [  1,       2,   3,   4,   5,   6,   7,    7,   6,   5,   4,   3,   2,   1]
    - [  9,          10,  11,  12,  13,  14,    14,  13,  12,  11,  10,   9,  15]
    - [ 16,            17,  18,  19,  20,  21,    21,  20,  19,  18,  17,  16,  22,  23]
    - [ 24,      25,     26,  27,  28,  29,  30,     30,  29,  28,  27,  26,  24]
    - [ 31,  32,  33,                      34,                       35,  36,  37,  38]


  plot_template: |2
    ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬──────┐
    │ {{0}} │ {{1}} │ {{2}} │ {{3}} │ {{4}} │ {{5}} │ {{6}} │ {{7}} │ {{8}} │ {{9}} │ {{10}} │ {{11}} │ {{12}} │ {{13}}    │
    ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬────┤
    │   {{14}} │ {{15}} │ {{16}} │ {{17}} │ {{18}} │ {{19}} │ {{20}} │ {{21}} │ {{22}} │ {{23}} │ {{24}} │ {{25}} │ {{26}} │ Ret│
    ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐   │
    │    {{27}} │ {{28}} │ {{29}} │ {{30}} │ {{31}} │ {{32}} │ {{33}} │ {{34}} │ {{35}} │ {{36}} │ {{37}} │ {{38}} │ {{39}} │ {{40}} │
    ├────┬─┴─┬─┴─┬─┴─┬─┴─┯─┴─┬─┴─┬─┴─┯─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴───┤
    │  {{41}} │ {{42}} │ {{43}} │ {{44}} │ {{45}} │ {{46}} │ {{47}} │ {{48}} │ {{49}} │ {{50}} │ {{51}} │ {{52}} │    {{53}}    │
    ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴─┬─┴──┬┴───┼────┬────┤
    │  {{54}} │ {{55}}  │ {{56}}  │           {{57}}           │  {{58}} │  {{59}} │  {{60}} │  {{61}} │
    └────┴────┴────┴───────────────────────┴────┴────┴────┴────┘


  plot_template_short: |2
    {{0}}{{1}}{{2}}{{3}}{{4}} {{5}}{{6}}{{7}}{{8}}{{9}}{{10}}{{11}}
    {{12}}{{13}}{{14}}{{15}}{{16}} {{17}}{{18}}{{19}}{{20}}{{21}}⇘
    {{22}}{{23}}{{24}}{{25}}{{26}} {{27}}{{28}}{{29}}{{30}}{{31}}

base_layout:
  keys:
    # Row 0 (number row)
    - - ["^", "ˇ", "↻", "˙", "˞", "̣"]
      - ["1", "°", "¹", "ª", "₁", "¬"]
      - ["2", "§", "²", "º", "₂", "∨"]
      - ["3", "ℓ", "³", "№", "₃", "∧"]
      - ["4", "»", "›", "", "♀", "⊥"]
      - ["5", "«", "‹", "·", "♂", "∡"]
      - ["6", "$", "¢", "£", "⚥", "∥"]
      - ["7", "€", "¥", "¤", "ϰ", "→"]
      - ["8", "„", "‚", "⇥", "⟨", "∞"]
      - ["9", "“", "‘", "/", "⟩", "∝"]
      - ["0", "”", "’", "*", "₀", "∅"]
      - ["-", "—", "-", "‑", "­", ""]
      - ["`", "¸", "°", "¨", "", "¯"]
      - ["←"]
    # Row 1
    - - ["⇥"]
      - ["x", "X", "…", "⇞", "ξ", "Ξ"]
      - ["v", "V", "_", "⌫", "", "√"]
      - ["l", "L", "[", "⇡", "λ", "Λ"]
      - ["c", "C", "]", "⌦", "χ", "ℂ"]
      - ["w", "W", "^", "⇟", "ω", "Ω"]
      - ["k", "K", "!", "¡", "κ", "×"]
      - ["h", "H", "<", "7", "ψ", "Ψ"]
      - ["g", "G", ">", "8", "γ", "Γ"]
      - ["f", "F", "=", "9", "φ", "Φ"]
      - ["q", "Q", "&", "+", "ϕ", "ℚ"]
      - ["y", "Y", "@", ".", "υ", "∇"]
      - ["ß", "ẞ", "ſ", "−", "ς", "∘"]
    # Row 2 (home row)
    - - ["⇩"]
      - ["u", "U", "\\", "⇱", "", "⊂"]
      - ["i", "I", "/", "⇠", "ι", "∫"]
      - ["a", "A", "{",  "⇣", "α", "∀"]
      - ["e", "E", "}", "⇢", "ε", "∃"]
      - ["o", "O", "*", "⇲", "ο", "∈"]
      - ["s", "S", "?", "¿", "σ", "Σ"]
      - ["n", "N", "(", "4", "ν", "ℕ"]
      - ["r", "R", ")", "5", "ρ", "ℝ"]
      - ["t", "T", "-", "6", "τ", "∂"]
      - ["d", "D", ":", ",", "δ", "Δ"]
      - ["⇘"]
      - ["´", "~", "/", "˝", "", "˘"]
      - ["\n"]
    # Row 3
    - - ["⇧"]
      - ["⇚"]
      - ["ü", "Ü", "#", "", "", "∪"]
      - ["ö", "Ö", "$", "\t", "ϵ", "∩"]
      - ["ä", "Ä", "|", "⎀", "η", "ℵ"]
      - ["p", "P", "~", "\n", "π", "Π"]
      - ["z", "Z", "`", "↶", "ζ", "ℤ"]
      - ["b", "B", "+", ":", "β", "⇐"]
      - ["m", "M", "%", "1", "μ", "⇔"]
      - [",", "–", '"', "2", "ϱ", "⇒"]
      - [".", "•", "'", "3", "ϑ", "↦"]
      - ["j", "J", ";", ";", "θ", "Θ"]
      - ["⇗"]
    # Row 4, containing the spacebar
    - - ["♕"]
      - [""]
      - ["♔"]
      - [" ", " ", " ", "0", " ", " "]
      - ["⇙"]
      - [""]
      - [""]
      - ["♛"]

  fixed_keys:
    - [ true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true]
    - [ true, false, false, false, false, false, false, false, false, false, false, false, false]
    - [ true, false, false, false, false, false, false, false, false, false, false,  true,  true,  true]
    - [ true,  true, false, false, false, false, false, false, false, false, false, false,  true]
    - [ true,  true,  true,                       true,                       true,  true,  true,  true]

  fixed_layers: [2, 3]

  modifiers:
    - Left: [[0,3]]
      Right: [[18,3]]
    - Left: [[0,2]]
      Right: [[18,2]]
    - Left: [[1,3]]
      Right: [[16,4]]
    - Left: [[0,3], [1,3]]
      Right: [[18,3], [16,4]]
    - Left: [[0,2], [1,3]]
      Right: [[18,2], [16,4]]
