keyboard:
  matrix_positions:
    - [[0,0],    [1,0], [2,0], [3,0], [4,0], [5,0], [6,0],   [13,0], [14,0], [15,0], [16,0], [17,0], [18,0], [19,0]]
    - [[0,1],          [2,1], [3,1], [4,1], [5,1], [6,1],   [13,1], [14,1], [15,1], [16,1], [17,1], [18,1], [19,1]]
    - [[0,2],            [2,2], [3,2], [4,2], [5,2], [6,2],   [13,2], [14,2], [15,2], [16,2], [17,2], [18,2], [19,2], [20,2]]
    - [[0,3],    [1,3],    [2,3], [3,3], [4,3], [5,3], [6,3],   [13,3], [14,3], [15,3], [16,3], [17,3], [18,3]]
    - [[0,4], [1,4], [2,4],                             [6,4],                        [16,4], [17,4], [18,4], [19,4]]

  positions:
    - [[   0,0],   [   1,0],   [   2,0],   [   3,0],   [   4,0],   [   5,0],   [   6,0],   [   7,0],   [   8,0],   [   9,0],   [   10,0],   [   11,0],   [   12,0],   [   13,0]]
    - [   [0.25,1],   [1.25,1],   [2.25,1],   [3.35,1],   [4.25,1],   [5.25,1],   [6.25,1],   [7.25,1],   [8.25,1],   [9.25,1],   [10.25,1],   [11.25,1],   [12.25,1]]
    - [      [ 0.5,2],   [ 1.5,2],   [ 2.5,2],   [ 3.5,2],   [ 4.5,2],   [ 5.5,2],   [ 6.5,2],   [ 7.5,2],   [ 8.5,2],   [ 9.5,2],   [ 10.5,2],   [ 11.5,2],   [ 12.5,2],   [ 13.5,2]]
    - [[   0,3],  [  1,3],  [1.75,3],   [2.75,3],   [3.75,3],   [4.75,3],   [5.75,3],   [6.75,3],   [7.75,3],   [8.75,3],   [ 9.75,3],   [10.75,3],   [11.75,3]]
    - [      [ 0.5,4],         [   2,4],   [   3,4],                                       [   7,4],                          [   10,4],   [ 11.5,4],   [   12,4],    [   13,4]]

  hands:
    - [Left,    Left, Left, Left, Left, Left, Left,   Right, Right, Right, Right, Right, Right, Right]
    - [Left,       Left, Left, Left, Left, Left,   Right, Right, Right, Right, Right, Right, Right]
    - [Left,          Left, Left, Left, Left, Left,   Right, Right, Right, Right, Right, Right, Right, Right]
    - [Left,    Left,    Left, Left, Left, Left, Left,   Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left,                     Right,                      Right, Right, Right, Right]

  fingers:
    - [Pinky,    Pinky, Pinky, Ring, Middle, Index, Index,   Index, Index, Middle, Ring, Pinky, Pinky, Pinky]
    - [Pinky,       Pinky, Ring, Middle, Index, Index,   Index, Index, Middle, Ring, Pinky, Pinky, Pinky]
    - [Pinky,          Pinky, Ring, Middle, Index, Index,   Index, Index, Middle, Ring, Pinky, Pinky, Pinky, Pinky]
    - [Pinky,    Pinky,   Pinky, Ring, Middle, Index, Index,   Index, Index, Middle, Ring, Pinky, Pinky]
    - [Pinky, Ring, Thumb,                          Thumb,                      Thumb, Middle, Ring, Pinky]

  key_costs:
    - [80,   70, 60, 50, 50, 50, 60,   60, 50, 50, 50, 60, 70, 80]
    - [24,      16, 10,  5, 12, 17,   20, 13,  5,  9, 11, 20, 36]
    - [ 9,         5,  3,  3,  3,  8,    8,  3,  3,  3,  5,  9, 30,  6]
    - [20,   16,    19, 22, 22, 14, 30,   10, 12, 20, 20, 17, 19]
    - [30, 20,  10,             3,              10, 20, 30, 40]

  unbalancing_positions:
    - [[-3, 3],  [-1.5,3],    [0, 3],   [0, 2],   [0, 1],   [0, 2],   [1, 3],       [-1, 3],   [0, 2],   [0, 1],   [0, 2],   [0, 3],   [1.5, 3],   [3, 3]]
    - [[-2, 2],      [0, 1],     [0, 0],   [0, 0],   [0,0.1],   [1, 1],       [-1.5,1], [-.5,.5], [0, 0],   [0, 0],   [0, 1],   [1, 1],   [2, 1.5]]
    - [[-1, 0],           [0, 0],   [0, 0],   [0, 0],   [0, 0],    [1, 0],       [-1, 0],  [0, 0],   [0, 0],   [0, 0],   [0, 0],   [1, 0],   [2, 0],  [3, 0]]
    - [[-1,-1],  [0,  0],     [0, 0],  [.5,-.5], [.5,-.5], [0, 0],   [2, -.5],      [0, 0],   [0, 0],   [0, 0],   [0, 0],   [0, 0],   [1, -1]]
    - [[-2,-2],  [0,-2], [0,-1],                                     [0, 0],                        [0,-1],   [0,-2],   [0,-3],   [1,-3]]

  symmetries:
    - [  1,       2,   3,   4,   5,   6,   7,    7,   6,   5,   4,   3,   2,   1]
    - [  9,          10,  11,  12,  13,  14,    14,  13,  12,  11,  10,   9,  15]
    - [ 16,            17,  18,  19,  20,  21,    21,  20,  19,  18,  17,  16,  22,  23]
    - [ 24,      25,     26,  27,  28,  29,  30,     30,  29,  28,  27,  26,  24]
    - [ 31,  32,  33,                      34,                       35,  36,  37,  38]


  plot_template: |2
    ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬──────┐
    │ {{0}} │ {{1}} │ {{2}} │ {{3}} │ {{4}} │ {{5}} │ {{6}} │ {{7}} │ {{8}} │ {{9}} │ {{10}} │ {{11}} │ {{12}} │ {{13}}    │
    ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬────┤
    │   {{14}} │ {{15}} │ {{16}} │ {{17}} │ {{18}} │ {{19}} │ {{20}} │ {{21}} │ {{22}} │ {{23}} │ {{24}} │ {{25}} │ {{26}} │ Ret│
    ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐   │
    │    {{27}} │ {{28}} │ {{29}} │ {{30}} │ {{31}} │ {{32}} │ {{33}} │ {{34}} │ {{35}} │ {{36}} │ {{37}} │ {{38}} │ {{39}} │ {{40}} │
    ├────┬─┴─┬─┴─┬─┴─┬─┴─┯─┴─┬─┴─┬─┴─┯─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴───┤
    │  {{41}} │ {{42}} │ {{43}} │ {{44}} │ {{45}} │ {{46}} │ {{47}} │ {{48}} │ {{49}} │ {{50}} │ {{51}} │ {{52}} │    {{53}}    │
    ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴─┬─┴──┬┴───┼────┬────┤
    │  {{54}} │ {{55}}  │ {{56}}  │           {{57}}           │  {{58}} │  {{59}} │  {{60}} │  {{61}} │
    └────┴────┴────┴───────────────────────┴────┴────┴────┴────┘


  plot_template_short: |2
    {{0}}{{1}}{{2}}{{3}}{{4}} {{5}}{{6}}{{7}}{{8}}{{9}}{{10}}{{11}}
    {{12}}{{13}}{{14}}{{15}}{{16}} {{17}}{{18}}{{19}}{{20}}{{21}}⇘
    {{22}}{{23}}{{24}}{{25}}{{26}} {{27}}{{28}}{{29}}{{30}}{{31}}

base_layout:
  keys:
    # Row 0 (number row)
    - - ["`", "¬"]
      - ["1", "!"]
      - ["2", '"']
      - ["3", "£"]
      - ["4", "$"]
      - ["5", "%"]
      - ["6", "^"]
      - ["7", "&"]
      - ["8", "*"]
      - ["9", "("]
      - ["0", ")"]
      - ["-", "—"]
      - ["=", "+"]
      - ["←"]
    # Row 1
    - - ["⇥"]
      - ["q", "Q"]
      - ["w", "W"]
      - ["e", "E"]
      - ["r", "R"]
      - ["t", "T"]
      - ["y", "Y"]
      - ["u", "U"]
      - ["i", "I"]
      - ["o", "O"]
      - ["p", "P"]
      - ["[", "{"]
      - ["]", "}"]
    # Row 2 (home row)
    - - [""]
      - ["a", "A"]
      - ["s", "S"]
      - ["d", "D"]
      - ["f", "F"]
      - ["g", "G"]
      - ["h", "H"]
      - ["j", "J"]
      - ["k", "K"]
      - ["l", "L"]
      - [";", ":"]
      - ["'", "@"]
      - ["#", "~"]
      - ["\n"]
    # Row 3
    - - ["⇧"]
      - ["\\", "|"]
      - ["z", "Z"]
      - ["x", "X"]
      - ["c", "C"]
      - ["v", "V"]
      - ["b", "B"]
      - ["n", "N"]
      - ["m", "M"]
      - [",", "<"]
      - [".", ">"]
      - ["/", "?"]
      - ["⇗"]
    # Row 4, containing the spacebar
    - - ["♕"]
      - [""]
      - ["♔"]
      - [" "]
      - [""]
      - [""]
      - [""]
      - ["♛"]

  fixed_keys:
    - [ true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true]
    - [ true, false, false, false, false, false, false, false, false, false, false,  true,  true]
    - [ true, false, false, false, false, false, false, false, false, false,  true,  true,  true,  true]
    - [ true,  true, false, false, false, false, false, false, false, false, false,  true,  true]
    - [ true,  true,  true,                       true,                       true,  true,  true,  true]

  # starting from 0
  fixed_layers: []

  modifiers:
    - Left:
        type: hold
        value: [[0,3]]
      Right:
        type: hold
        value: [[18,3]]
