[default]
eval_parameters = "../../config/evaluation_parameters.yml"
layout_configs = [
    ["standard", "../../config/standard_keyboard.yml"],
    ["ortho", "../../config/ortho.yml"],
    ["moonlander", "../../config/moonlander.yml"],
    ["crkbd", "../../config/crkbd.yml"]
]
default_layout_config = "standard"
static_dir = "static"
ngrams = "../../corpus/deu_mixed_wiki_web_0.6_eng_news_typical_wiki_web_0.4"
secret = "super_duper_secret"
allowed_cors_origins = "http://localhost:8080"

[default.databases.sqlx]
url = "postgres://postgres:super_secret@localhost:15432/postgres"
