metrics:

  oxey_inward_rolls:
    enabled: true
    weight: 100.0
    normalization:
      type: weight_all
      value: 1.0
    params:
      exclude_thumbs: false

  oxey_outward_rolls:
    enabled: true
    weight: 100.0
    normalization:
      type: weight_all
      value: 1.0
    params:
      exclude_thumbs: false

  oxey_onehands:
    enabled: true
    weight: 100.0
    normalization:
      type: weight_all
      value: 1.0
    params:
      exclude_thumbs: false

  oxey_alternates:
    enabled: true
    weight: 100.0
    normalization:
      type: weight_all
      value: 1.0
    params:
      exclude_thumbs: false

  oxey_alternates_sfs:
    enabled: true
    weight: 100.0
    normalization:
      type: weight_all
      value: 1.0
    params:
      exclude_thumbs: false

ngrams:
  # Increase the weight of bigrams that have both an absolute weight and relative weight exceed
  # specified thresholds.
  increase_common_ngrams:
    enabled: false
    # Bigrams with a relative weight exceeding this threshold are considered
    critical_fraction: 0.001
    # The weight for bigrams exceeding both thresholds is multiplied by this factor
    factor: 2.0
    # Bigrams with an absolute weight exceeding this threshold are considered
    total_weight_threshold: 20.0


ngram_mapper:
  # Exclude ngrams that contain a line break, followed by a non-line-break character.
  # This encodes a mental pause which usually comes after hitting the "Enter" key, before
  # continuing to write.
  exclude_line_breaks: false

  # Split symbols belonging to higher layers of the layout into combinations involving modifiers
  # required to activate the layer
  split_modifiers:
    enabled: false
    # Multiply the ngram's weight with this factor whenever the resulting ngram involves two
    # modifiers that are required for the same symbol
    same_key_mod_factor: 0.03125



