keyboard:
  matrix_positions:
    - [[0,0], [1,0], [2,0], [3,0], [4,0], [5,0],                 [8,0], [9,0], [10,0], [11,0], [12,0], [13,0]]
    - [[0,1], [1,1], [2,1], [3,1], [4,1], [5,1],                 [8,1], [9,1], [10,1], [11,1], [12,1], [13,1]]
    - [[0,2], [1,2], [2,2], [3,2], [4,2], [5,2],                 [8,2], [9,2], [10,2], [11,2], [12,2], [13,2]]
    - [                            [4,3], [5,3], [6,3],   [7,3], [8,3], [9,3], [10,3]                        ]

  positions:
    - [[0,0], [1,0], [2,0], [3,0], [4,0], [5,0],                 [8,0], [9,0], [10,0], [11,0], [12,0], [13,0]]
    - [[0,1], [1,1], [2,1], [3,1], [4,1], [5,1],                 [8,1], [9,1], [10,1], [11,1], [12,1], [13,1]]
    - [[0,2], [1,2], [2,2], [3,2], [4,2], [5,2],                 [8,2], [9,2], [10,2], [11,2], [12,2], [13,2]]
    - [                            [4,3], [5,3], [6,3],   [7,3], [8,3], [9,3], [10,3]                        ]

  hands:
    - [Left, Left, Left, Left, Left, Left,                Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left,                Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left,                Right, Right, Right, Right, Right, Right]
    - [                        Left, Left, Left,   Right, Right, Right, Right                     ]

  fingers:
    - [Pinky, Pinky, Ring,  Middle, Pointer, Pointer,                 Pointer, Pointer, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Pointer, Pointer,                 Pointer, Pointer, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Pointer, Pointer,                 Pointer, Pointer, Middle, Ring,  Pinky, Pinky]
    - [                             Thumb,   Thumb,   Thumb,   Thumb, Thumb,   Thumb,                              ]

  key_costs:
    - [20, 17,  9,  5, 12, 17,           17, 12,  5,  9, 17, 20]
    - [ 9,  5,  3,  3,  3,  6,            6,  3,  3,  3,  5,  9]
    - [20, 11, 22, 22, 10, 15,           15, 10, 22, 22, 11, 20]
    - [                 6,  3,  6,    6,  3,  6                ]

  unbalancing_positions:
    - [   2,   1,   0,   0, 0.1,   2,               2, 0.1,   0,   0,   1,   2]
    - [   1,   0,   0,   0,   0,   1,               1,   0,   0,   0,   0,   1]
    - [   2,   0,   0,   0,   0, 1.5,             1.5,   0,   0,   0,   0,   2]
    - [                       0,   0,   0,     0,   0,   0,                   ]

  symmetries:
    - [  9, 10, 11, 12, 13, 14,           14, 13, 12, 11, 10,  9]
    - [ 15, 16, 17, 18, 19, 20,           20, 19, 18, 17, 16, 15]
    - [ 21, 22, 23, 24, 25, 26,           26, 25, 24, 23, 22, 21]
    - [                 27, 28, 29,   29, 28, 27                ]



  plot_template: |2
                ┌───┐                         ┌───┐
            ┌───┤ {{3}} ├───┬───┐         ┌───┬───┤ {{8}} ├───┐
    ┌───┬───┤ {{2}} ├───┤ {{4}} │ {{5}} │         │ {{6}} │ {{7}} ├───┤ {{9}} ├───┬───┐
    │ {{0}} │ {{1}} ├───┤ {{15}} ├───┼───┤         ├───┼───┤ {{20}} ├───┤ {{10}} │ {{11}} │
    ├───┼───┤ {{14}} ├───┤ {{16}} │ {{17}} │         │ {{18}} │ {{19}} ├───┤ {{21}} ├───┼───┤
    │ {{12}} │ {{13}} ├───┤ {{27}} ├─━─┼───┤         ├───┼─━─┤ {{32}} ├───┤ {{22}} │ {{23}} │
    ├───┼───┤ {{26}} ├───┤ {{28}} │ {{29}} │         │ {{30}} │ {{31}} ├───┤ {{33}} ├───┼───┤
    │ {{24}} │ {{25}} ├───┘   └───┴───┘         └───┴───┘   └───┤ {{34}} │ {{35}} │
    └───┴───┘       ┌───┬───┬───┐ ┌───┬───┬───┐       └───┴───┘
                    │ {{36}} │ {{37}} │ {{38}} │ │ {{39}} │ {{40}} │ {{41}} │
                    └───┴───┴───┘ └───┴───┴───┘


  plot_template_short: |2
    {{0}}{{1}}{{2}}{{3}}{{4}}{{5}} {{6}}{{7}}{{8}}{{9}}{{10}}{{11}}
    ⇘{{12}}{{13}}{{14}}{{15}}{{16}} {{17}}{{18}}{{19}}{{20}}{{21}}⇘
     {{22}}{{23}}{{24}}{{25}}{{26}} {{27}}{{28}}{{29}}{{30}}{{31}}

base_layout:
  keys:
    # Reihe 1
    - - ["x", "X", "…", "⇞", "ξ", "Ξ"]
      - ["v", "V", "_", "⌫", "", "√"]
      - ["l", "L", "[", "⇡", "λ", "Λ"]
      - ["c", "C", "]", "⌦", "χ", "ℂ"]
      - ["w", "W", "^", "⇟", "ω", "Ω"]
      - ["k", "K", "!", "¡", "κ", "×"]
      - ["h", "H", "<", "7", "ψ", "Ψ"]
      - ["g", "G", ">", "8", "γ", "Γ"]
      - ["f", "F", "=", "9", "φ", "Φ"]
      - ["q", "Q", "&", "+", "ϕ", "ℚ"]
      - ["y", "Y", "@", ".", "υ", "∇"]
      - ["ß", "ẞ", "ſ", "−", "ς", "∘"]
    # Reihe 2
    - - ["⇩"]
      - ["u", "U", "\\", "⇱", "", "⊂"]
      - ["i", "I", "/", "⇠", "ι", "∫"]
      - ["a", "A", "{",  "⇣", "α", "∀"]
      - ["e", "E", "}", "⇢", "ε", "∃"]
      - ["o", "O", "*", "⇲", "ο", "∈"]
      - ["s", "S", "?", "¿", "σ", "Σ"]
      - ["n", "N", "(", "4", "ν", "ℕ"]
      - ["r", "R", ")", "5", "ρ", "ℝ"]
      - ["t", "T", "-", "6", "τ", "∂"]
      - ["d", "D", ":", ",", "δ", "Δ"]
      - ["⇘"]
    # Reihe 3
    - - [""]
      - ["ü", "Ü", "#", "", "", "∪"]
      - ["ö", "Ö", "$", "\t", "ϵ", "∩"]
      - ["ä", "Ä", "|", "⎀", "η", "ℵ"]
      - ["p", "P", "~", "\n", "π", "Π"]
      - ["z", "Z", "`", "↶", "ζ", "ℤ"]
      - ["b", "B", "+", ":", "β", "⇐"]
      - ["m", "M", "%", "1", "μ", "⇔"]
      - [",", "–", '"', "2", "ϱ", "⇒"]
      - [".", "•", "'", "3", "ϑ", "↦"]
      - ["j", "J", ";", ";", "θ", "Θ"]
      - [""]
    # Reihe 4 mit Leertaste
    - - ["⇚"]
      - [" ", " ", " ", "0", " ", " "]
      - ["♕"]
      - ["⇧"]
      - ["⏎"]
      - ["⇙"]

  fixed_keys:
    - [ false, false, false, false, false, false,        false, false, false, false, false, false]
    - [  true, false, false, false, false, false,        false, false, false, false, false,  true]
    - [  true, false, false, false, false, false,        false, false, false, false, false,  true]
    - [  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true]

  fixed_layers: [2, 3]

  modifiers:
    - Left: ["⇧"]
      Right: ["⇧"]
    - Left: ["⇩"]
      Right: ["⇘"]
    - Left: ["⇚"]
      Right: ["⇙"]
    - Left: ["⇧", "⇚"]
      Right: ["⇧", "⇙"]
    - Left: ["⇩", "⇚"]
      Right: ["⇘", "⇙"]

  layer_costs: [0, 20, 9, 16, 29, 25]
