# Swap out this many keys-pairs on every iteration.
# For simulated annealing it's best to keep the variation between iterations
# as small as possible. Thus, one single swap may be best.
key_switches: 1

### Parameters for the solver.
# Stop if there was no accepted solution after this many iterations
stall_accepted: 1000    
# Start reannealing after no new best solution has been found for this many iterations
reannealing_best: 4000

### Parameters for the [Executor].
# Set maximum number of iterations (defaults to `std::u64::MAX`)
max_iters: 100000
