keyboard:
  matrix_positions:
    - [[0,0], [1,0], [2,0], [3,0], [4,0], [5,0], [6,0],                             [11,0], [12,0], [13,0], [14,0], [15,0], [16,0], [17,0]]
    - [[0,1], [1,1], [2,1], [3,1], [4,1], [5,1], [6,1],                             [11,1], [12,1], [13,1], [14,1], [15,1], [16,1], [17,1]]
    - [[0,2], [1,2], [2,2], [3,2], [4,2], [5,2], [6,2],                             [11,2], [12,2], [13,2], [14,2], [15,2], [16,2], [17,2]]
    - [[0,3], [1,3], [2,3], [3,3], [4,3], [5,3],                                            [12,3], [13,3], [14,3], [15,3], [16,3], [17,3]]
    - [[0,4], [1,4], [2,4], [3,4], [4,4], [5,4], [6,4],[7,4], [8,4], [9,4], [10,4], [11,4], [12,4], [13,4], [14,4], [15,4], [16,4], [17,4]]
                                                                                                   
  positions:                                                                                       
    - [[0,0], [1,0], [2,0], [3,0], [4,0], [5,0], [6,0],                             [11,0], [12,0], [13,0], [14,0], [15,0], [16,0], [17,0]]
    - [[0,1], [1,1], [2,1], [3,1], [4,1], [5,1], [6,1],                             [11,1], [12,1], [13,1], [14,1], [15,1], [16,1], [17,1]]
    - [[0,2], [1,2], [2,2], [3,2], [4,2], [5,2], [6,2],                             [11,2], [12,2], [13,2], [14,2], [15,2], [16,2], [17,2]]
    - [[0,3], [1,3], [2,3], [3,3], [4,3], [5,3],                                            [12,3], [13,3], [14,3], [15,3], [16,3], [17,3]]
    - [[0,4], [1,4], [2,4], [3,4], [4,4], [5,4], [6,4],[7,4], [8,4], [9,4], [10,4], [11,4], [12,4], [13,4], [14,4], [15,4], [16,4], [17,4]]

  hands:
    - [Left, Left, Left, Left, Left, Left, Left,                            Right, Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left, Left,                            Right, Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left, Left,                            Right, Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left,                                         Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left, Left, Left, Left,  Right, Right, Right, Right, Right, Right, Right, Right, Right]

  fingers:
    - [Pinky, Pinky, Ring,  Middle, Pointer, Pointer, Pointer,                          Pointer, Pointer, Pointer, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Pointer, Pointer, Pointer,                          Pointer, Pointer, Pointer, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Pointer, Pointer, Pointer,                          Pointer, Pointer, Pointer, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Pointer, Pointer,                                            Pointer, Pointer, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Thumb,  Thumb,   Thumb,   Thumb, Thumb, Thumb, Thumb, Thumb,  Thumb,   Thumb,   Thumb, Thumb,  Ring,  Pinky, Pinky]

  key_costs:
    - [80, 70, 60, 50, 50, 60, 100,                      100, 60, 50, 50, 50, 50, 60]
    - [20, 11,  9,  5, 12, 17,  90,                       90, 17, 12,  5,  9, 11, 20]
    - [ 9,  5,  3,  3,  3,  6,  80,                       80,  6,  3,  3,  3,  5,  9]
    - [20, 17, 22, 22, 10, 15,                                15, 10, 22, 22, 17, 20]
    - [30, 25, 20,  4,  3,       3, 8, 60, 70, 70, 60,  8, 3,      3,  4, 20, 25, 30]

  unbalancing_positions:
    - [   2,   2,   2,   0,   0,   0, 5,                         5, 0,   0,   0,   2,   2,   2]
    - [   2,   1,   0,   0, 0.1,   2, 4,                         4, 2, 0.1,   0,   0,   1,   2]
    - [   1,   0,   0,   0,   0,   1, 3,                         3, 1,   0,   0,   0,   0,   1]
    - [   2,   0,   0,   0,   0, 1.5,                             1.5,   0,   0,   0,   0,   2]
    - [   3, 2.5,   2,   0,   0,      0, 1.1, 2, 3, 3, 2, 1.1, 0,        0,   0,   2, 2.5,   3]

  symmetries:
    - [  1,  2,  3,  4,  5,  6,  7,                          7,  6,  5,  4,  3,  2,  1]
    - [  9, 10, 11, 12, 13, 14, 15,                         15, 14, 13, 12, 11, 10,  9]
    - [ 16, 17, 18, 19, 20, 21, 22,                         22, 21, 20, 19, 18, 17, 16]
    - [ 23, 24, 25, 26, 27, 28,                                 28, 27, 26, 25, 24, 23]
    - [ 29, 30, 31, 32, 33,     34, 35, 36, 37, 37, 36, 35, 34,     33, 32, 31, 30, 29]



  plot_template: |2
                ┌───┐                                          ┌───┐
            ┌───┤ {{3}} ├───┬───┐                          ┌───┬───┤ {{10}} ├───┐
    ┌───┬───┤ {{2}} ├───┤ {{4}} │ {{5}} ├───┐                  ┌───┤ {{8}} │ {{9}} ├───┤ {{11}} ├───┬───┐
    │ {{0}} │ {{1}} ├───┤ {{17}} ├───┼───┤ {{6}} │                  │ {{7}} ├───┼───┤ {{24}} ├───┤ {{12}} │ {{13}} │
    ├───┼───┤ {{16}} ├───┤ {{18}} │ {{19}} ├───┤                  ├───┤ {{22}} │ {{23}} ├───┤ {{25}} ├───┼───┤
    │ {{14}} │ {{15}} ├───┤ {{31}} ├───┼───┤ {{20}} │                  │ {{21}} ├───┼───┤ {{38}} ├───┤ {{26}} │ {{27}} │
    ├───┼───┤ {{30}} ├───┤ {{32}} │ {{33}} ├───┤                  ├───┤ {{36}} │ {{37}} ├───┤ {{39}} ├───┼───┤
    │ {{28}} │ {{29}} ├───┤ {{45}} ├─━─┼───┤ {{34}} │                  │ {{35}} ├───┼─━─┤ {{50}} ├───┤ {{40}} │ {{41}} │
    ├───┼───┤ {{44}} ├───┤ {{46}} │ {{47}} ├───┘                  └───┤ {{48}} │ {{49}} ├───┤ {{51}} ├───┼───┤
    │ {{42}} │ {{43}} ├───┤ {{57}} ├───┼───┘┌───────┐        ┌───────┐└───┼───┤ {{68}} ├───┤ {{52}} │ {{53}} │
    ├───┼───┤ {{56}} ├───┤ {{58}} │    │   {{62}}   │        │   {{63}}   │    │ {{67}} ├───┤ {{69}} ├───┼───┤
    │ {{54}} │ {{55}} ├───┘   └───┘    ├───┬───┼───┐┌───┼───┬───┤    └───┘   └───┤ {{70}} │ {{71}} │
    └───┴───┘                │   │   │   ││   │   │   │                └───┴───┘
                             │ {{59}} │ {{60}} │ {{61}} ││ {{64}} │ {{65}} │ {{66}} │   
                             └───┴───┴───┘└───┴───┴───┘  


  plot_template_short: |2
    {{12}}{{13}}{{14}}{{15}}{{16}}{{17}} {{18}}{{19}}{{20}}{{21}}{{22}}{{23}}
    {{24}}{{25}}{{26}}{{27}}{{28}}{{29}} {{30}}{{31}}{{32}}{{33}}{{34}}{{35}}
    {{36}}{{37}}{{38}}{{39}}{{40}}{{41}} {{42}}{{43}}{{44}}{{45}}{{46}}{{47}}

base_layout:
  keys:
    # Zahlenreihe
    - - ["^", "ˇ", "↻", "˙", "˞", "̣"]
      - ["1", "°", "¹", "ª", "₁", "¬"]
      - ["2", "§", "²", "º", "₂", "∨"]
      - ["3", "ℓ", "³", "№", "₃", "∧"]
      - ["4", "»", "›", "", "♀", "⊥"]
      - ["5", "«", "‹", "·", "♂", "∡"]
      - [""]
      - [""]
      - ["6", "$", "¢", "£", "⚥", "∥"]
      - ["7", "€", "¥", "¤", "ϰ", "→"]
      - ["8", "„", "‚", "⇥", "⟨", "∞"]
      - ["9", "“", "‘", "/", "⟩", "∝"]
      - ["0", "”", "`", "*", "₀", "∅"]
      - ["-", "—", "´", "‑", "­", ""]
    # Reihe 1
    - - ["⇥"]
      - ["v", "V", "_", "⌫", "", "√"]
      - ["l", "L", "[", "⇡", "λ", "Λ"]
      - ["c", "C", "]", "⌦", "χ", "ℂ"]
      - ["w", "W", "^", "⇟", "ω", "Ω"]
      - ["k", "K", "!", "¡", "κ", "×"]
      - [""]
      - [""]
      - ["h", "H", "<", "7", "ψ", "Ψ"]
      - ["g", "G", ">", "8", "γ", "Γ"]
      - ["f", "F", "=", "9", "φ", "Φ"]
      - ["q", "Q", "&", "+", "ϕ", "ℚ"]
      - ["y", "Y", "@", ".", "υ", "∇"]
      - ["ß", "ẞ", "ſ", "−", "ς", "∘"]
    # Reihe 2
    - - [""]
      - ["u", "U", "\\", "⇱", "", "⊂"]
      - ["i", "I", "/", "⇠", "ι", "∫"]
      - ["a", "A", "{",  "⇣", "α", "∀"]
      - ["e", "E", "}", "⇢", "ε", "∃"]
      - ["o", "O", "*", "⇲", "ο", "∈"]
      - [""]
      - [""]
      - ["s", "S", "?", "¿", "σ", "Σ"]
      - ["n", "N", "(", "4", "ν", "ℕ"]
      - ["r", "R", ")", "5", "ρ", "ℝ"]
      - ["t", "T", "-", "6", "τ", "∂"]
      - ["d", "D", ":", ",", "δ", "Δ"]
      - ["x", "X", "…", "⇞", "ξ", "Ξ"]
    # Reihe 3
    - - [""]
      - ["ü", "Ü", "#", "", "", "∪"]
      - ["ö", "Ö", "$", "\t", "ϵ", "∩"]
      - ["ä", "Ä", "|", "⎀", "η", "ℵ"]
      - ["p", "P", "~", "\n", "π", "Π"]
      - ["z", "Z", "`", "↶", "ζ", "ℤ"]
      - ["b", "B", "+", ":", "β", "⇐"]
      - ["m", "M", "%", "1", "μ", "⇔"]
      - [",", "–", '"', "2", "ϱ", "⇒"]
      - [".", "•", "'", "3", "ϑ", "↦"]
      - ["j", "J", ";", ";", "θ", "Θ"]
      - [""]
    # Reihe 4 mit Leertaste und Modifiern
    - - ["♕"]
      - [""]
      - ["♔"]
      - ["⇩"]
      - ["⇚"]
      - ["⇧"]
      - ["⏎"]
      - [""]
      - [""]
      - [""]
      - [""]
      - ["⌫"]
      - [" ", " ", " ", "0", " ", " "]
      - [""]
      - ["♖"]
      - [""]
      - [""]
      - ["♕"]

  fixed_keys:
    - [  true,  true,  true,  true,  true,  true, true,                           true, true,  true,  true,  true,  true,  true]
    - [  true, false, false, false, false, false, true,                           true, false, false, false, false, false, false]
    - [  true, false, false, false, false, false, true,                           true, false, false, false, false, false, false]
    - [  true, false, false, false, false, false,                                       false, false, false, false, false, true]
    - [  true,  true,  true,  true,  true,  true,  true, true, true,  true, true, true, true,  true,  true,  true,  true,  true]

  fixed_layers: [2, 3]

  modifiers:
    - Left: ["⇧"]
      Right: ["⇧"]
    - Left: ["⇩"]
      Right: ["⇩"]
    - Left: ["⇚"]
      Right: ["⇚"]
    - Left: ["♖"]
      Right: ["♖"]
    - Left: ["⇩", "⇚"]
      Right: ["⇩", "⇚"]

  layer_costs: [0, 20, 9, 16, 29, 25]
