keyboard:
  matrix_positions:
    - [[0,0], [1,0], [2,0], [3,0], [4,0], [5,0],        [7,0], [8,0], [9,0], [10,0], [11,0], [12,0]]
    - [[0,1], [1,1], [2,1], [3,1], [4,1], [5,1],        [7,1], [8,1], [9,1], [10,1], [11,1], [12,1]]
    - [[0,2], [1,2], [2,2], [3,2], [4,2], [5,2],        [7,2], [8,2], [9,2], [10,2], [11,2], [12,2]]
    - [[0,3], [1,3], [2,3], [3,3], [4,3], [5,3],        [7,3], [8,3], [9,3], [10,3], [11,3], [12,3]]
    - [[0,4], [1,4], [2,4], [3,4], [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4], [12,4]]

  positions:
    - [[0,0], [1,0], [2,0], [3,0], [4,0], [5,0],        [7,0], [8,0], [9,0], [10,0], [11,0], [12,0]]
    - [[0,1], [1,1], [2,1], [3,1], [4,1], [5,1],        [7,1], [8,1], [9,1], [10,1], [11,1], [12,1]]
    - [[0,2], [1,2], [2,2], [3,2], [4,2], [5,2],        [7,2], [8,2], [9,2], [10,2], [11,2], [12,2]]
    - [[0,3], [1,3], [2,3], [3,3], [4,3], [5,3],        [7,3], [8,3], [9,3], [10,3], [11,3], [12,3]]
    - [[0,4], [1,4], [2,4], [3,4], [4,4], [5,4], [7,4], [7,4], [8,4], [9,4], [10,4], [11,4], [12,4]]

  hands:
    - [Left, Left, Left, Left, Left, Left,        Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left,        Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left,        Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left,        Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left, Right, Right, Right, Right, Right, Right, Right]

  fingers:
    - [Pinky, Pinky, Ring,  Middle, Pointer, Pointer,        Pointer, Pointer, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Pointer, Pointer,        Pointer, Pointer, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Pointer, Pointer,        Pointer, Pointer, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Pointer, Pointer,        Pointer, Pointer, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Thumb,  Thumb,   Thumb,   Thumb, Thumb,   Thumb,   Thumb,  Ring,  Pinky, Pinky]

  key_costs:
    - [80, 70, 60, 50, 50, 60,     60, 50, 50, 50, 50, 60]
    - [20, 11,  9,  5, 12, 17,     17, 12,  5,  9, 11, 20]
    - [ 9,  5,  3,  3,  3,  6,      6,  3,  3,  3,  5,  9]
    - [20, 17, 22, 22, 10, 15,     15, 10, 22, 22, 17, 20]
    - [30, 25, 20,  4,  3,  3,  3,  3,  3,  4, 20, 25, 30]

  unbalancing_positions:
    - [   2,   2,   2,   0,   0,   0,        0,   0,   0,   2,   2,   2]
    - [   2,   1,   0,   0, 0.1,   2,        2, 0.1,   0,   0,   1,   2]
    - [   1,   0,   0,   0,   0,   1,        1,   0,   0,   0,   0,   1]
    - [   2,   0,   0,   0,   0, 1.5,      1.5,   0,   0,   0,   0,   2]
    - [   3, 2.5,   2,   0,   0,   0,   0,   0,   0,   0,   2, 2.5,   3]

  symmetries:
    - [  1,  2,  3,  4,  5,  6,      6,  5,  4,  3,  2,  1]
    - [  9, 10, 11, 12, 13, 14,     14, 13, 12, 11, 10,  9]
    - [ 15, 16, 17, 18, 19, 20,     20, 19, 18, 17, 16, 15]
    - [ 21, 22, 23, 24, 25, 26,     26, 25, 24, 23, 22, 21]
    - [ 27, 28, 29, 30, 31, 32, 33, 32, 31, 30, 29, 28, 27]



  plot_template: |2
                  ┌───┐                       ┌───┐
              ┌───┤ {{3}} ├───┬───┐       ┌───┬───┤ {{8}} ├───┐
    ┌─────┬───┤ {{2}} ├───┤ {{4}} │ {{5}} │       │ {{6}} │ {{7}} ├───┤ {{9}} ├───┬─────┐
    │  {{0}}  │ {{1}} ├───┤ {{15}} ├───┼───┤       ├───┼───┤ {{20}} ├───┤ {{10}} │  {{11}}  │
    ├─────┼───┤ {{14}} ├───┤ {{16}} │ {{17}} │       │ {{18}} │ {{19}} ├───┤ {{21}} ├───┼─────┤
    │  {{12}}  │ {{13}} ├───┤ {{27}} ├───┼───┤       ├───┼───┤ {{32}} ├───┤ {{22}} │  {{23}}  │
    ├─────┼───┤ {{26}} ├───┤ {{28}} │ {{29}} │       │ {{30}} │ {{31}} ├───┤ {{33}} ├───┼─────┤
    │  {{24}}  │ {{25}} ├───┤ {{39}} ├─━─┼───┤       ├───┼─━─┤ {{44}} ├───┤ {{34}} │  {{35}}  │
    ├─────┼───┤ {{38}} ├───┤ {{40}} │ {{41}} │       │ {{42}} │ {{43}} ├───┤ {{45}} ├───┼─────┤
    │  {{36}}  │ {{37}} ├───┘   └───┴───┘       └───┴───┘   └───┤ {{46}} │  {{47}}  │
    ├─────┼───┼───┬───┬───┬───┐ ┌───┐ ┌───┬───┬───┬───┼───┼─────┤
    │  {{48}}  │ {{49}} │ {{50}} │ {{51}} │ {{52}} │ {{53}} │ │ {{54}} │ │ {{55}} │ {{56}} │ {{57}} │ {{58}} │ {{59}} │  {{60}}  │
    └─────┴───┴───┴───┴───┴───┘ └───┘ └───┴───┴───┴───┴───┴─────┘


  plot_template_short: |2
    {{0}}{{1}}{{2}}{{3}}{{4}}{{5}} {{6}}{{7}}{{8}}{{9}}{{10}}{{11}}
    ⇘{{12}}{{13}}{{14}}{{15}}{{16}} {{17}}{{18}}{{19}}{{20}}{{21}}⇘
     {{22}}{{23}}{{24}}{{25}}{{26}} {{27}}{{28}}{{29}}{{30}}{{31}}

base_layout:
  keys:
    # Zahlenreihe
    - - ["^", "ˇ", "↻", "˙", "˞", "̣"]
      - ["1", "°", "¹", "ª", "₁", "¬"]
      - ["2", "§", "²", "º", "₂", "∨"]
      - ["3", "ℓ", "³", "№", "₃", "∧"]
      - ["4", "»", "›", "", "♀", "⊥"]
      - ["5", "«", "‹", "·", "♂", "∡"]
      - ["6", "$", "¢", "£", "⚥", "∥"]
      - ["7", "€", "¥", "¤", "ϰ", "→"]
      - ["8", "„", "‚", "⇥", "⟨", "∞"]
      - ["9", "“", "‘", "/", "⟩", "∝"]
      - ["0", "”", "’", "*", "₀", "∅"]
      - ["-", "—", "-", "‑", "­", ""]
    # Reihe 1
    - - ["⇥"]
      - ["v", "V", "_", "⌫", "", "√"]
      - ["l", "L", "[", "⇡", "λ", "Λ"]
      - ["c", "C", "]", "⌦", "χ", "ℂ"]
      - ["w", "W", "^", "⇟", "ω", "Ω"]
      - ["k", "K", "!", "¡", "κ", "×"]
      - ["h", "H", "<", "7", "ψ", "Ψ"]
      - ["g", "G", ">", "8", "γ", "Γ"]
      - ["f", "F", "=", "9", "φ", "Φ"]
      - ["q", "Q", "&", "+", "ϕ", "ℚ"]
      - ["y", "Y", "@", ".", "υ", "∇"]
      - ["ß", "ẞ", "ſ", "−", "ς", "∘"]
    # Reihe 2
    - - ["⇩"]
      - ["u", "U", "\\", "⇱", "", "⊂"]
      - ["i", "I", "/", "⇠", "ι", "∫"]
      - ["a", "A", "{",  "⇣", "α", "∀"]
      - ["e", "E", "}", "⇢", "ε", "∃"]
      - ["o", "O", "*", "⇲", "ο", "∈"]
      - ["s", "S", "?", "¿", "σ", "Σ"]
      - ["n", "N", "(", "4", "ν", "ℕ"]
      - ["r", "R", ")", "5", "ρ", "ℝ"]
      - ["t", "T", "-", "6", "τ", "∂"]
      - ["d", "D", ":", ",", "δ", "Δ"]
      - ["x", "X", "…", "⇞", "ξ", "Ξ"]
    # Reihe 3
    - - ["⇧"]
      - ["ü", "Ü", "#", "", "", "∪"]
      - ["ö", "Ö", "$", "\t", "ϵ", "∩"]
      - ["ä", "Ä", "|", "⎀", "η", "ℵ"]
      - ["p", "P", "~", "\n", "π", "Π"]
      - ["z", "Z", "`", "↶", "ζ", "ℤ"]
      - ["b", "B", "+", ":", "β", "⇐"]
      - ["m", "M", "%", "1", "μ", "⇔"]
      - [",", "–", '"', "2", "ϱ", "⇒"]
      - [".", "•", "'", "3", "ϑ", "↦"]
      - ["j", "J", ";", ";", "θ", "Θ"]
      - ["⇗"]
    # Reihe 4 mit Leertaste
    - - [""]
      - [""]
      - [""]
      - ["⇚"]
      - [" ", " ", " ", "0", " ", " "]
      - ["♕"]
      - [""]
      - ["♔"]
      - [" ", " ", " ", "0", " ", " "]
      - ["⇙"]
      - [""]
      - [""]
      - ["♛"]

  fixed_keys:
    - [  true,  true,  true,  true,  true,  true,         true,  true,  true,  true,  true,  true]
    - [  true, false, false, false, false, false,        false, false, false, false, false, false]
    - [  true, false, false, false, false, false,        false, false, false, false, false, false]
    - [  true, false, false, false, false, false,        false, false, false, false, false,  true]
    - [  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true]

  fixed_layers: [2, 3]

  modifiers:
    - Left: ["⇧"]
      Right: ["⇗"]
    - Left: ["⇩"]
      Right: ["⇩"]
    - Left: ["⇚"]
      Right: ["⇙"]
    - Left: ["⇧", "⇚"]
      Right: ["⇗", "⇙"]
    - Left: ["⇩", "⇚"]
      Right: ["⇩", "⇙"]

  layer_costs: [0, 20, 9, 16, 29, 25]
