version: "3.4"

services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 15432:5432
    command: postgres -c 'max_connections=100'
    environment:
      POSTGRES_PASSWORD: super_secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default

volumes:
  pgdata:
