[default]
eval_parameters = "../config/evaluation_parameters.yml"
layout_config = "../config/standard_keyboard.yml"
unigrams = "../1-gramme.arne.txt"
bigrams = "../2-gramme.arne.txt"
trigrams = "../3-gramme.arne.txt"
reeval_layouts = false
secret = "super_duper_secret"

[default.databases.sqlx]
url = "postgres://postgres:super_secret@localhost:15432/postgres"
