[default]
eval_parameters = "../config/evaluation_parameters.yml"
layout_config = "../config/standard_keyboard.yml"
static_dir = "static"
unigrams = "../1-gramme.arne.no-special.txt"
bigrams = "../2-gramme.arne.no-special.txt"
trigrams = "../3-gramme.arne.no-special.txt"
reeval_layouts = false
secret = "super_duper_secret"

[default.databases.sqlx]
url = "postgres://postgres:super_secret@localhost:15432/postgres"
