name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  webpage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
          version: 'latest'

      - name: Build WASM
        run: wasm-pack build --release
        working-directory: ./evolve_keyboard_layout_wasm

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install node packages
        run: npm install
        working-directory: ./evolve_keyboard_layout_wasm/www

      - name: Build Webpage
        run: npm run build
        working-directory: ./evolve_keyboard_layout_wasm/www

      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        if: github.repository_owner == 'dariogoetz'
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./evolve_keyboard_layout_wasm/www/dist # The folder the action should deploy.
